// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"leeforge-example-service/ent/post"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PostCreate is the builder for creating a Post entity.
type PostCreate struct {
	config
	mutation *PostMutation
	hooks    []Hook
}

// SetCreatedByID sets the "created_by_id" field.
func (_c *PostCreate) SetCreatedByID(v uuid.UUID) *PostCreate {
	_c.mutation.SetCreatedByID(v)
	return _c
}

// SetNillableCreatedByID sets the "created_by_id" field if the given value is not nil.
func (_c *PostCreate) SetNillableCreatedByID(v *uuid.UUID) *PostCreate {
	if v != nil {
		_c.SetCreatedByID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PostCreate) SetCreatedAt(v time.Time) *PostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableCreatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedByID sets the "updated_by_id" field.
func (_c *PostCreate) SetUpdatedByID(v uuid.UUID) *PostCreate {
	_c.mutation.SetUpdatedByID(v)
	return _c
}

// SetNillableUpdatedByID sets the "updated_by_id" field if the given value is not nil.
func (_c *PostCreate) SetNillableUpdatedByID(v *uuid.UUID) *PostCreate {
	if v != nil {
		_c.SetUpdatedByID(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PostCreate) SetUpdatedAt(v time.Time) *PostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableUpdatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedByID sets the "deleted_by_id" field.
func (_c *PostCreate) SetDeletedByID(v uuid.UUID) *PostCreate {
	_c.mutation.SetDeletedByID(v)
	return _c
}

// SetNillableDeletedByID sets the "deleted_by_id" field if the given value is not nil.
func (_c *PostCreate) SetNillableDeletedByID(v *uuid.UUID) *PostCreate {
	if v != nil {
		_c.SetDeletedByID(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PostCreate) SetDeletedAt(v time.Time) *PostCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableDeletedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *PostCreate) SetPublishedAt(v time.Time) *PostCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *PostCreate) SetNillablePublishedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetArchivedAt sets the "archived_at" field.
func (_c *PostCreate) SetArchivedAt(v time.Time) *PostCreate {
	_c.mutation.SetArchivedAt(v)
	return _c
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableArchivedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetArchivedAt(*v)
	}
	return _c
}

// SetOwnerDomainID sets the "owner_domain_id" field.
func (_c *PostCreate) SetOwnerDomainID(v uuid.UUID) *PostCreate {
	_c.mutation.SetOwnerDomainID(v)
	return _c
}

// SetNillableOwnerDomainID sets the "owner_domain_id" field if the given value is not nil.
func (_c *PostCreate) SetNillableOwnerDomainID(v *uuid.UUID) *PostCreate {
	if v != nil {
		_c.SetOwnerDomainID(*v)
	}
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *PostCreate) SetAuthorID(v uuid.UUID) *PostCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *PostCreate) SetTitle(v string) *PostCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *PostCreate) SetContent(v string) *PostCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *PostCreate) SetSlug(v string) *PostCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PostCreate) SetStatus(v post.Status) *PostCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PostCreate) SetNillableStatus(v *post.Status) *PostCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *PostCreate) SetViewCount(v int) *PostCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableViewCount(v *int) *PostCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *PostCreate) SetTags(v []string) *PostCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PostCreate) SetID(v uuid.UUID) *PostCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PostCreate) SetNillableID(v *uuid.UUID) *PostCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PostMutation object of the builder.
func (_c *PostCreate) Mutation() *PostMutation {
	return _c.mutation
}

// Save creates the Post in the database.
func (_c *PostCreate) Save(ctx context.Context) (*Post, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostCreate) SaveX(ctx context.Context) *Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PostCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := post.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := post.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := post.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := post.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := post.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostCreate) check() error {
	if _, ok := _c.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "Post.author_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Post.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Post.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := post.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Post.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Post.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := post.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Post.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Post.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "Post.view_count"`)}
	}
	return nil
}

func (_c *PostCreate) sqlSave(ctx context.Context) (*Post, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PostCreate) createSpec() (*Post, *sqlgraph.CreateSpec) {
	var (
		_node = &Post{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(post.Table, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedByID(); ok {
		_spec.SetField(post.FieldCreatedByID, field.TypeUUID, value)
		_node.CreatedByID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(post.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedByID(); ok {
		_spec.SetField(post.FieldUpdatedByID, field.TypeUUID, value)
		_node.UpdatedByID = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedByID(); ok {
		_spec.SetField(post.FieldDeletedByID, field.TypeUUID, value)
		_node.DeletedByID = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(post.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = value
	}
	if value, ok := _c.mutation.ArchivedAt(); ok {
		_spec.SetField(post.FieldArchivedAt, field.TypeTime, value)
		_node.ArchivedAt = value
	}
	if value, ok := _c.mutation.OwnerDomainID(); ok {
		_spec.SetField(post.FieldOwnerDomainID, field.TypeUUID, value)
		_node.OwnerDomainID = &value
	}
	if value, ok := _c.mutation.AuthorID(); ok {
		_spec.SetField(post.FieldAuthorID, field.TypeUUID, value)
		_node.AuthorID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(post.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(post.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(post.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	return _node, _spec
}

// PostCreateBulk is the builder for creating many Post entities in bulk.
type PostCreateBulk struct {
	config
	err      error
	builders []*PostCreate
}

// Save creates the Post entities in the database.
func (_c *PostCreateBulk) Save(ctx context.Context) ([]*Post, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Post, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostCreateBulk) SaveX(ctx context.Context) []*Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
