database:
  host: "localhost"
  port: "15436"
  username: "<db-username>"
  password: "<db-password>"
  # name: "example"
  name: "postgres"
  sslmode: "disable"
  params: ""
  auto_migrate: true
  max_open_conns: 10
  max_idle_conns: 5
