server:
  port: "8080"
  mode: release
  cors:
    enabled: true
    allowed_origins:
      - "http://localhost:3000"
      - "http://localhost:8081"
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers:
      - "Accept"
      - "Authorization"
      - "Content-Type"
      - "X-CSRF-Token"
      - "X-Client-Type"
    exposed_headers: ["Link"]
    allow_credentials: true
    max_age: 300
